import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123#456'),
      isAdmin: true,
      userType: 'Admin',
      isActiveUser: true,
      // channel: 'direct',
    },
    {
      name: 'Agent',
      email: 'merchant@example.com',
      password: bcrypt.hashSync('123#456'),
      isAdmin: false,
      userType: 'Merchant',
      isActiveUser: true,
      // channel: 'local',
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123#456'),
      isAdmin: false,
      userType: 'Normal',
      isActiveUser: true,
      // channel: 'local',
    },
  ],
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      imagelist: ['/images/shirt1.jpg', '/images/shirt1.jpg'],
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      banner: '/images/banner1.jpg',
      merchantEmail: 'merchant@example.com',
      isActiveProduct: true,
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      imagelist: ['/images/shirt2.jpg', '/images/shirt2.jpg'],
      price: 80,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
      isFeatured: true,
      banner: '/images/banner2.jpg',
      merchantEmail: 'merchant@example.com',
      isActiveProduct: true,
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      imagelist: ['/images/shirt3.jpg', '/images/shirt3.jpg'],
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shirt',
      merchantEmail: 'merchant@example.com',
      isActiveProduct: true,
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      imagelist: ['/images/pants1.jpg', '/images/pants1.jpg'],
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart looking pants',
      merchantEmail: 'merchant@example.com',
      isActiveProduct: true,
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      imagelist: ['/images/pants2.jpg', '/images/pants2.jpg'],
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular pants',
      merchantEmail: 'merchant@example.com',
      isActiveProduct: true,
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      imagelist: ['/images/pants3.jpg', '/images/pants3.jpg'],
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
      merchantEmail: 'merchant@example.com',
      isActiveProduct: true,
    },
  ],
};

export default data;
